stages:
  - deploy

variables:       # ここはGitLab CIの変数で設定推奨
  REGISTRY_HOST: elie3141
  DEFAULT_CI_IMAGE: elie3141/kubernetes:0.1 
  GCP_KMS_KEY: projects//locations/global/keyRings/secret_key/cryptoKeys/secret_key

before_script:
  # サービスアカウントキーで認証
  - echo  > /gcp-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=/gcp-key.json
  - echo 
  - ls -lR
  - gcloud auth activate-service-account --key-file=/gcp-key.json
  - gcloud config set project 
  # GKE クラスタ認証情報取得
  - gcloud container clusters get-credentials  --zone 
  #- cp  ~/.kube/config
  - export KUBECONFIG=~/.kube/config
  - curl -LO https://github.com/getsops/sops/releases/download/v3.10.2/sops-v3.10.2.linux.amd64
  - chmod +x sops-v3.10.2.linux.amd64
  - mv sops-v3.10.2.linux.amd64 ./sops
  - ./sops -d k8s/postgres-secret.enc.yaml > k8s/postgres-secret.yaml
deploy:
  stage: deploy  
  script:
    #- kubectl apply -f k8s/
    - find k8s -type f ! -name *.enc.yaml -exec kubectl apply -f {} \;
    - kubectl get all
default:
  image: 
  timeout: 90m

